package códigos.Interfaces;

public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        super("Loja de Brinquedos - Login");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaLogin = new javax.swing.JPanel();
        pnlLoginIMG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlLoginFORM = new javax.swing.JPanel();
        txtLoginEmail = new javax.swing.JLabel();
        txfLoginEmail = new javax.swing.JTextField();
        txtLoginSenha = new javax.swing.JLabel();
        btnLoginEntrar = new javax.swing.JButton();
        txtLoginBemVindo = new javax.swing.JLabel();
        txtLoginEsqc = new javax.swing.JLabel();
        btnLoginEsqc = new javax.swing.JButton();
        txtLoginSubtit = new javax.swing.JLabel();
        txfLoginSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLoginIMG.setBackground(new java.awt.Color(229, 127, 14));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Loja.png"))); // NOI18N

        javax.swing.GroupLayout pnlLoginIMGLayout = new javax.swing.GroupLayout(pnlLoginIMG);
        pnlLoginIMG.setLayout(pnlLoginIMGLayout);
        pnlLoginIMGLayout.setHorizontalGroup(
            pnlLoginIMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        pnlLoginIMGLayout.setVerticalGroup(
            pnlLoginIMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLoginFORM.setBackground(new java.awt.Color(254, 254, 254));

        txtLoginEmail.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        txtLoginEmail.setText("Email");

        txfLoginEmail.setToolTipText("Digite seu email.");
        txfLoginEmail.setMargin(new java.awt.Insets(2, 12, 2, 6));
        txfLoginEmail.addActionListener(this::txfLoginEmailActionPerformed);

        txtLoginSenha.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        txtLoginSenha.setText("Senha");

        btnLoginEntrar.setBackground(new java.awt.Color(229, 127, 14));
        btnLoginEntrar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnLoginEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginEntrar.setText("ENTRAR");
        btnLoginEntrar.setBorder(null);
        btnLoginEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLoginEntrar.addActionListener(this::btnLoginEntrarActionPerformed);

        txtLoginBemVindo.setBackground(new java.awt.Color(229, 127, 14));
        txtLoginBemVindo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        txtLoginBemVindo.setForeground(new java.awt.Color(229, 127, 14));
        txtLoginBemVindo.setText("Bem vindo(a)!");
        txtLoginBemVindo.setIconTextGap(0);
        txtLoginBemVindo.setPreferredSize(new java.awt.Dimension(124, 1254));

        txtLoginEsqc.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtLoginEsqc.setText("Esqueceu sua senha?");

        btnLoginEsqc.setBackground(new java.awt.Color(254, 254, 254));
        btnLoginEsqc.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        btnLoginEsqc.setForeground(new java.awt.Color(229, 127, 14));
        btnLoginEsqc.setText("Recupere-a.");
        btnLoginEsqc.setBorder(null);
        btnLoginEsqc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLoginEsqc.setFocusable(false);
        btnLoginEsqc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoginEsqc.addActionListener(this::btnLoginEsqcActionPerformed);

        txtLoginSubtit.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtLoginSubtit.setText("Entre em sua conta para acessar os demais recursos da ferramenta.");

        txfLoginSenha.setMargin(new java.awt.Insets(2, 12, 2, 6));

        javax.swing.GroupLayout pnlLoginFORMLayout = new javax.swing.GroupLayout(pnlLoginFORM);
        pnlLoginFORM.setLayout(pnlLoginFORMLayout);
        pnlLoginFORMLayout.setHorizontalGroup(
            pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFORMLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createSequentialGroup()
                        .addGroup(pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createSequentialGroup()
                                .addGroup(pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLoginEmail)
                                        .addComponent(txtLoginSenha)
                                        .addComponent(txfLoginEmail)
                                        .addComponent(txfLoginSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createSequentialGroup()
                                        .addComponent(btnLoginEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createSequentialGroup()
                                .addComponent(txtLoginBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))
                            .addComponent(txtLoginSubtit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createSequentialGroup()
                        .addComponent(txtLoginEsqc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoginEsqc)
                        .addGap(215, 215, 215))))
        );
        pnlLoginFORMLayout.setVerticalGroup(
            pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFORMLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(txtLoginBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLoginSubtit)
                .addGap(44, 44, 44)
                .addComponent(txtLoginEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtLoginSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLoginEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginFORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginEsqc)
                    .addComponent(btnLoginEsqc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TelaLoginLayout = new javax.swing.GroupLayout(TelaLogin);
        TelaLogin.setLayout(TelaLoginLayout);
        TelaLoginLayout.setHorizontalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLoginLayout.createSequentialGroup()
                .addComponent(pnlLoginIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLoginFORM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaLoginLayout.setVerticalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginFORM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLoginIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfLoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLoginEmailActionPerformed

    private void btnLoginEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginEntrarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal principal = new TelaPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLoginEntrarActionPerformed

    private void btnLoginEsqcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginEsqcActionPerformed
        // TODO add your handling code here:
        TelaAviso aviso = new TelaAviso("erro");
        aviso.setLocationRelativeTo(null);
        aviso.setVisible(true);
    }//GEN-LAST:event_btnLoginEsqcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelaLogin;
    private javax.swing.JButton btnLoginEntrar;
    private javax.swing.JButton btnLoginEsqc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlLoginFORM;
    private javax.swing.JPanel pnlLoginIMG;
    private javax.swing.JTextField txfLoginEmail;
    private javax.swing.JPasswordField txfLoginSenha;
    private javax.swing.JLabel txtLoginBemVindo;
    private javax.swing.JLabel txtLoginEmail;
    private javax.swing.JLabel txtLoginEsqc;
    private javax.swing.JLabel txtLoginSenha;
    private javax.swing.JLabel txtLoginSubtit;
    // End of variables declaration//GEN-END:variables
}
